version: "3.9"
services: 
  dictionary:
    build: "dictionary_service"
    environment: 
      - CONSUL_NAME=consul
    links:
      - consul
    depends_on: 
      - consul
    command: ["./wait-for-it.sh", "consul:8500", "--", "python", "entrypoint.sh"]
  expression:
    build: "expression_service"
    ports:
      - "8000:8000"
    environment: 
      - CONSUL_NAME=consul
    links:
      - consul
    depends_on: 
      - consul
      - dictionary
    command: ["./wait-for-it.sh", "consul:8500", "--", "python", "entrypoint.sh"]
  # nginx_lb:
    # image: "nginx_lb"
    # ports:
    #   - "8008:80"
    # links:
    #   - consul
    # depends_on: 
    #   - consul
  consul:
    image: "consul:latest"
    environment: 
      - CONSUL_BIND_INTERFACE=eth0
    ports:
      - "8500:8500"